<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\aft_L.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder031: THREE.Mesh
      Cylinder031_1: THREE.Mesh
      Cylinder031_2: THREE.Mesh
      Cylinder031_3: THREE.Mesh
    }
    materials: {
      ['Material.023']: THREE.MeshStandardMaterial
      ['Material.017']: THREE.MeshStandardMaterial
      ['Heatshield Tiles']: THREE.MeshStandardMaterial
      ['Material.008']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/aft_L.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[0, 0, -Math.PI]} scale={-1}>
      <T.Mesh geometry={gltf.nodes.Cylinder031.geometry} material={gltf.materials['Material.023']} />
      <T.Mesh geometry={gltf.nodes.Cylinder031_1.geometry} material={gltf.materials['Material.017']} />
      <T.Mesh geometry={gltf.nodes.Cylinder031_2.geometry} material={gltf.materials['Heatshield Tiles']} />
      <T.Mesh geometry={gltf.nodes.Cylinder031_3.geometry} material={gltf.materials['Material.008']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
