<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\body.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube001: THREE.Mesh
      Cube001_1: THREE.Mesh
      Cube001_2: THREE.Mesh
      Cube001_3: THREE.Mesh
      Cube001_4: THREE.Mesh
      Cube001_5: THREE.Mesh
      Cube001_6: THREE.Mesh
      Cube001_7: THREE.Mesh
      Cube001_8: THREE.Mesh
      Cube001_9: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      Emissive: THREE.MeshStandardMaterial
      ['Emissive.001']: THREE.MeshStandardMaterial
      ['Emissive.002']: THREE.MeshStandardMaterial
      ['Emissive.003']: THREE.MeshStandardMaterial
      ['Emissive.004']: THREE.MeshStandardMaterial
      ['Emissive.005']: THREE.MeshStandardMaterial
      ['Emissive.006']: THREE.MeshStandardMaterial
      ['Emissive.007']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/body.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube001.geometry} material={gltf.materials.Material} />
    <T.Mesh geometry={gltf.nodes.Cube001_1.geometry} material={gltf.materials.Emissive} />
    <T.Mesh geometry={gltf.nodes.Cube001_2.geometry} material={gltf.materials['Emissive.001']} />
    <T.Mesh geometry={gltf.nodes.Cube001_3.geometry} material={gltf.materials['Emissive.002']} />
    <T.Mesh geometry={gltf.nodes.Cube001_4.geometry} material={gltf.materials['Emissive.003']} />
    <T.Mesh geometry={gltf.nodes.Cube001_5.geometry} material={gltf.materials['Emissive.004']} />
    <T.Mesh geometry={gltf.nodes.Cube001_6.geometry} material={gltf.materials['Emissive.005']} />
    <T.Mesh geometry={gltf.nodes.Cube001_7.geometry} material={gltf.materials['Emissive.006']} />
    <T.Mesh geometry={gltf.nodes.Cube001_8.geometry} material={gltf.materials['Emissive.007']} />
    <T.Mesh geometry={gltf.nodes.Cube001_9.geometry} material={gltf.materials['Material.007']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
