<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\nosecone.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder007: THREE.Mesh
      Cylinder007_1: THREE.Mesh
      Cylinder007_2: THREE.Mesh
      Cylinder007_3: THREE.Mesh
      Cylinder007_4: THREE.Mesh
      Cylinder007_5: THREE.Mesh
    }
    materials: {
      ['Cryo Section1']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Heatshield Tiles']: THREE.MeshStandardMaterial
      ['Material.056']: THREE.MeshStandardMaterial
      ['Serial Number']: THREE.MeshStandardMaterial
      Logo: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/nosecone.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.91}>
      <T.Mesh geometry={gltf.nodes.Cylinder007.geometry} material={gltf.materials['Cryo Section1']} />
      <T.Mesh geometry={gltf.nodes.Cylinder007_1.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Cylinder007_2.geometry} material={gltf.materials['Heatshield Tiles']} />
      <T.Mesh geometry={gltf.nodes.Cylinder007_3.geometry} material={gltf.materials['Material.056']} />
      <T.Mesh geometry={gltf.nodes.Cylinder007_4.geometry} material={gltf.materials['Serial Number']} />
      <T.Mesh geometry={gltf.nodes.Cylinder007_5.geometry} material={gltf.materials.Logo} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
