<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\olm.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder: THREE.Mesh
      Cylinder001: THREE.Mesh
      Torus: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      Emissive: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/olm.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials['Material.001']}
      scale={[1.6, 0.25, 1.6]}
    />
    <T.Mesh geometry={gltf.nodes.Cylinder001.geometry} material={gltf.materials['Material.001']} scale={[1, 0.25, 1]} />
    <T.Mesh geometry={gltf.nodes.Torus.geometry} material={gltf.materials.Emissive} scale={[1.3, 0.1, 1.3]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
