<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\qd.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
      Cube001: THREE.Mesh
      Cube002: THREE.Mesh
      Cube003: THREE.Mesh
      Cube004: THREE.Mesh
    }
    materials: {
      ['Material.002']: THREE.MeshStandardMaterial
      Emissive: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/qd.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials['Material.002']} scale={[0.5, 1, 1]} />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials.Emissive}
      position={[0.5, 1, 0]}
      scale={[0.05, 0.05, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials.Emissive}
      position={[0, -1, 0]}
      scale={[0.05, 0.05, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.materials.Emissive}
      position={[-0.5, 1, 0]}
      scale={[0.05, 0.05, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube004.geometry}
      material={gltf.materials.Emissive}
      position={[-0.5, -1, 0]}
      scale={[0.05, 0.05, 1]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
