<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\IFT-X\static\models\rsea.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder: THREE.Mesh
      Cylinder_1: THREE.Mesh
      Cylinder_2: THREE.Mesh
      Cylinder_3: THREE.Mesh
      Cylinder_4: THREE.Mesh
      Cylinder_5: THREE.Mesh
      Cylinder_6: THREE.Mesh
      Cylinder_7: THREE.Mesh
      Cylinder_8: THREE.Mesh
      Cylinder_9: THREE.Mesh
      Cylinder_10: THREE.Mesh
      Cylinder_11: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.033']: THREE.MeshStandardMaterial
      ['Material.034']: THREE.MeshStandardMaterial
      ['Material.036']: THREE.MeshStandardMaterial
      ['Material.037']: THREE.MeshStandardMaterial
      ['Material.030']: THREE.MeshStandardMaterial
      ['Material.038']: THREE.MeshStandardMaterial
      ['Material.039']: THREE.MeshStandardMaterial
      ['Material.040']: THREE.MeshStandardMaterial
      ['Material.041']: THREE.MeshStandardMaterial
      Material: THREE.MeshStandardMaterial
      ['Material.021']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/rsea.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cylinder.geometry} material={gltf.materials['Material.001']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_1.geometry} material={gltf.materials['Material.033']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_2.geometry} material={gltf.materials['Material.034']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_3.geometry} material={gltf.materials['Material.036']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_4.geometry} material={gltf.materials['Material.037']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_5.geometry} material={gltf.materials['Material.030']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_6.geometry} material={gltf.materials['Material.038']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_7.geometry} material={gltf.materials['Material.039']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_8.geometry} material={gltf.materials['Material.040']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_9.geometry} material={gltf.materials['Material.041']} />
    <T.Mesh geometry={gltf.nodes.Cylinder_10.geometry} material={gltf.materials.Material} />
    <T.Mesh geometry={gltf.nodes.Cylinder_11.geometry} material={gltf.materials['Material.021']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
