<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\rvac.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder002: THREE.Mesh
      Cylinder002_1: THREE.Mesh
      Cylinder002_2: THREE.Mesh
      Cylinder002_3: THREE.Mesh
      Cylinder002_4: THREE.Mesh
      Cylinder002_5: THREE.Mesh
      Cylinder002_6: THREE.Mesh
      Cylinder002_7: THREE.Mesh
      Cylinder002_8: THREE.Mesh
      Cylinder002_9: THREE.Mesh
      Cylinder002_10: THREE.Mesh
      Cylinder002_11: THREE.Mesh
      Cylinder002_12: THREE.Mesh
      Cylinder002_13: THREE.Mesh
    }
    materials: {
      ['Material.100']: THREE.MeshStandardMaterial
      ['Material.099']: THREE.MeshStandardMaterial
      ['Material.098']: THREE.MeshStandardMaterial
      ['Material.097']: THREE.MeshStandardMaterial
      ['Material.096']: THREE.MeshStandardMaterial
      ['Material.095']: THREE.MeshStandardMaterial
      ['Material.094']: THREE.MeshStandardMaterial
      ['Material.093']: THREE.MeshStandardMaterial
      ['Material.092']: THREE.MeshStandardMaterial
      ['Material.091']: THREE.MeshStandardMaterial
      Heat1: THREE.MeshStandardMaterial
      Heat2: THREE.MeshStandardMaterial
      Material: THREE.MeshStandardMaterial
      ['Material.021']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/rvac.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.04}>
      <T.Mesh geometry={gltf.nodes.Cylinder002.geometry} material={gltf.materials['Material.100']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_1.geometry} material={gltf.materials['Material.099']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_2.geometry} material={gltf.materials['Material.098']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_3.geometry} material={gltf.materials['Material.097']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_4.geometry} material={gltf.materials['Material.096']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_5.geometry} material={gltf.materials['Material.095']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_6.geometry} material={gltf.materials['Material.094']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_7.geometry} material={gltf.materials['Material.093']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_8.geometry} material={gltf.materials['Material.092']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_9.geometry} material={gltf.materials['Material.091']} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_10.geometry} material={gltf.materials.Heat1} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_11.geometry} material={gltf.materials.Heat2} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_12.geometry} material={gltf.materials.Material} />
      <T.Mesh geometry={gltf.nodes.Cylinder002_13.geometry} material={gltf.materials['Material.021']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
