<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\DuDu\Olympiads_School\Computer\Websites\IFT-X\static\models\top.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
      Cube004: THREE.Mesh
      Cube010_1: THREE.Mesh
      Cube010_2: THREE.Mesh
      Cube010_3: THREE.Mesh
      Cube014: THREE.Mesh
      Cube014_1: THREE.Mesh
      Cube014_2: THREE.Mesh
      Cube017: THREE.Mesh
      Cube017_1: THREE.Mesh
      Cube017_2: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      E: THREE.MeshStandardMaterial
      ['Emissive.003']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
      ['Emissive.007']: THREE.MeshStandardMaterial
      ['Emissive.001']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['Emissive.006']: THREE.MeshStandardMaterial
      Emissive: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Emissive.004']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/top.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials.Material} />
    <T.Mesh
      geometry={gltf.nodes.Cube004.geometry}
      material={gltf.materials.E}
      position={[1.5, 0, 1.5]}
      scale={[0.05, 1, 0.05]}
    />
    <T.Group position={[-1.05, 0, 0.75]} scale={[0.05, 1, 0.05]}>
      <T.Mesh geometry={gltf.nodes.Cube010_1.geometry} material={gltf.materials['Emissive.003']} />
      <T.Mesh geometry={gltf.nodes.Cube010_2.geometry} material={gltf.materials['Material.007']} />
      <T.Mesh geometry={gltf.nodes.Cube010_3.geometry} material={gltf.materials['Emissive.007']} />
    </T.Group>
    <T.Group position={[-1.05, 0, -0.75]} scale={[0.05, 1, 0.05]}>
      <T.Mesh geometry={gltf.nodes.Cube014.geometry} material={gltf.materials['Emissive.001']} />
      <T.Mesh geometry={gltf.nodes.Cube014_1.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Cube014_2.geometry} material={gltf.materials['Emissive.006']} />
    </T.Group>
    <T.Group position={[1.05, 0, -0.75]} scale={[0.05, 1, 0.05]}>
      <T.Mesh geometry={gltf.nodes.Cube017.geometry} material={gltf.materials.Emissive} />
      <T.Mesh geometry={gltf.nodes.Cube017_1.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Cube017_2.geometry} material={gltf.materials['Emissive.004']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
